$terminal = kitty
$fileManager = dolphin
$menu = fuzzel

source = ./colors.conf
source = ./config/env.conf
source = ./config/monitors.conf
source = ./config/autostart.conf
source = ./config/appearance.conf
source = ./config/input.conf
source = ./config/keybinds.conf
source = ./config/rules.conf
