[font]
normal = { family = "JetBrainsMono Nerd Font" }
size = 14

[env]
TERM="xterm-256color"

[terminal]
shell = { program = "nu", args = ["-c", "tmux new-session -A -s main"] }

[window]
decorations = "None"
dimensions = { lines = 40, columns = 170 }
dynamic_padding = true
opacity = 0.9

