-- Generated by Matugen

require("base16-colorscheme").setup({
	base00 = "#19120c",
	base01 = "#130d07",
	base02 = "#211a14",
	base03 = "#51453a",
	base04 = "#d5c3b5",
	base05 = "#efe0d5",
	base06 = "#372f28",
	base07 = "#403830",

	base08 = "#b5c389",
	base09 = "#c0cc9a",
	base0A = "#e1c1a4",
	base0B = "#fcb975",
	base0C = "#414b24",
	base0D = "#693c00",
	base0E = "#59422c",
	base0F = "#d4a77e",
})

-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
	for _, v in pairs(groups) do
		vim.api.nvim_set_hl(0, v, value)
	end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, "Visual", {
	bg = "#693c00",
	fg = "#ffdcbe", -- normal text contrast
})

-- Make "string" text contrast better
set_hl_mutliple({ "String", "TSString" }, {
	fg = "#a0b267",
})

-- Grey out comments
set_hl_mutliple({ "TSComment", "Comment" }, {
	fg = "#9d8e81",
	italic = true,
})

-- Color in other highlight groups as you see fit!

set_hl_mutliple({ "TSMethod", "Method" }, {
	fg = "#c0cc9a",
})

set_hl_mutliple({ "TSFunction", "Function" }, {
	fg = "#e1c1a4",
})

set_hl_mutliple({ "Keyword", "TSKeyword", "TSKeywordFunction", "TSRepeat" }, {
	fg = "#855318",
})
