-- Generated by Matugen

require("base16-colorscheme").setup({
	base00 = "#18120e",
	base01 = "#130d09",
	base02 = "#211a16",
	base03 = "#53443a",
	base04 = "#d8c2b6",
	base05 = "#eee0d9",
	base06 = "#372f2a",
	base07 = "#403833",

	base08 = "#6fd8ea",
	base09 = "#85deed",
	base0A = "#eabea2",
	base0B = "#ffc59f",
	base0C = "#68c2d1",
	base0D = "#f3a36b",
	base0E = "#5f402b",
	base0F = "#e1a178",
})

-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
	for _, v in pairs(groups) do
		vim.api.nvim_set_hl(0, v, value)
	end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, "Visual", {
	bg = "#f3a36b",
	fg = "#451f00", -- normal text contrast
})

-- Make "string" text contrast better
set_hl_mutliple({ "String", "TSString" }, {
	fg = "#42cce3",
})

-- Grey out comments
set_hl_mutliple({ "TSComment", "Comment" }, {
	fg = "#a08d82",
	italic = true,
})

-- Color in other highlight groups as you see fit!

set_hl_mutliple({ "TSMethod", "Method" }, {
	fg = "#85deed",
})

set_hl_mutliple({ "TSFunction", "Function" }, {
	fg = "#eabea2",
})

set_hl_mutliple({ "Keyword", "TSKeyword", "TSKeywordFunction", "TSRepeat" }, {
	fg = "#8d4f1e",
})
