-- Generated by Matugen

require("base16-colorscheme").setup({
	base00 = "#1b110c",
	base01 = "#150c08",
	base02 = "#241914",
	base03 = "#574239",
	base04 = "#ddc1b4",
	base05 = "#f3ded6",
	base06 = "#3a2e28",
	base07 = "#433731",

	base08 = "#62c7ff",
	base09 = "#7bd0ff",
	base0A = "#fcb795",
	base0B = "#ffb691",
	base0C = "#1a9bce",
	base0D = "#e17130",
	base0E = "#6a3a21",
	base0F = "#fb9563",
})

-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
	for _, v in pairs(groups) do
		vim.api.nvim_set_hl(0, v, value)
	end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, "Visual", {
	bg = "#e17130",
	fg = "#000000", -- normal text contrast
})

-- Make "string" text contrast better
set_hl_mutliple({ "String", "TSString" }, {
	fg = "#2fb5ff",
})

-- Grey out comments
set_hl_mutliple({ "TSComment", "Comment" }, {
	fg = "#a58b80",
	italic = true,
})

-- Color in other highlight groups as you see fit!

set_hl_mutliple({ "TSMethod", "Method" }, {
	fg = "#7bd0ff",
})

set_hl_mutliple({ "TSFunction", "Function" }, {
	fg = "#fcb795",
})

set_hl_mutliple({ "Keyword", "TSKeyword", "TSKeywordFunction", "TSRepeat" }, {
	fg = "#9e4200",
})
